variables:
  partition: ["ib", "eth"]
  nodes: [2, 4, 6, 8]

haicgu:
  scheduler: slurm

  default_conf:
    cpus_per_task: 128
    time: "00:30:00"
    account: "dcn"
    gpus: 0
    modules: 
      - "GCC/14.1.0"
      - "OpenMPI/5.0.3"

  configs:
    - name: "{partition}_{nodes}nodes"
      partition: "cn-{partition}"
      nodes: "{nodes}"
      ntasks: "{nodes}"

nanjing:
  scheduler: local

  default_conf:
    env:
      - "PATH=/root/hpc/build/gcc/bin:/root/hpc/build/bin:$PATH"
      - "LD_LIBRARY_PATH=/root/hpc/build/gcc/lib64:/root/hpc/build/lib:$LD_LIBRARY_PATH"

  configs:
    - name: "nanjing_{nodes}nodes"