sequential: true

variables:
  nodes: [1, 2, 4, 8]
  models_dp: ['vit_b_16_32', 'vit_b_16_128', 'vit_l_16_32', 'vit_l_16_128', 'vit_h_16_32', 'vit_h_16_128']
  num_buckets: [8, 32, 128]
  base_path: ["HPC-benchmarks/DNNProxy/DNNProxy"]
  models_fsdp: ['gpt2_l_32', 'gpt2_l_128']
  num_units: [6, 12, 18]
  partition: ["nanjing-inter", "nanjing-intra"]
  # which: ['inter', 'intra']

jobs:
  - config: "{partition}_{nodes}nodes"
    config_jobs:
      - tag: "dp_{nodes}nodes"
        command: "mpirun --allow-run-as-root -x PATH -x LD_LIBRARY_PATH -np {nodes} --hostfile /root/hpc/tpasquali/HPC-benchmarks/NJ/{nodes}hosts_{partition} ./dp {models_dp} {num_buckets} {base_path}"

      - tag: "fsdp_{nodes}nodes"
        command: "mpirun --allow-run-as-root -x PATH -x LD_LIBRARY_PATH -np {nodes} --hostfile /root/hpc/tpasquali/HPC-benchmarks/NJ/{nodes}hosts_{partition} ./fsdp {models_fsdp} {num_units} {nodes} {base_path}"

