variables:
  nodes: [1, 2, 4, 8]
  partition: ["ib", "eth"]

haicgu:
  scheduler: slurm

  default_conf:
    #reservation: "dcn_6"
    account: "dcn"
    cpus_per_task: 128
    gpus: 0
    time: "01:00:00"
    modules: 
      - "GCC/14.1.0"
      - "OpenMPI/5.0.3"
      - "OpenBLAS/0.3.27"
    env:
      - "OMP_PROC_BIND=true"
      - "OMP_NUM_THREADS=128"
    exclude:
      - "cn17"
      - "cn19"
    custom_headers:
      - "#SBATCH --ntasks-per-node=1"

  configs:
    - name: "{partition}_{nodes}nodes"
      partition: "cn-{partition}"
      nodes: "{nodes}"
      ntasks: "{nodes}"

leonardo:
  scheduler: slurm

  default_conf:
    account: "try25_HNS"
    cpus_per_task: 32
    gpus: 0
    time: "00:05:00"
    partition: "boost_usr_prod"
    qos: "normal"
    modules: 
      - "gcc/12.2.0"
      - "openmpi/4.1.6--gcc--12.2.0-cuda-12.2"
    env:
      - "OMP_PROC_BIND=true"
      - "OMP_NUM_THREADS=32"

  configs:
    - name: "boost_usr_prod_{nodes}nodes"
      nodes: "{nodes}"
      ntasks: "{nodes}"

