# Sequential is mandatory
sequential: true

variables:
  nodes: [1, 2, 4, 8]
  # partition: ["eth", "ib"]
  partition: ["boost_usr_prod"]

  grid_size: [128]
  min_runtime: [0] # In seconds

command: "mpirun -np {nodes} ./xhpcg --nx={grid_size} --ny={grid_size} --nz={grid_size} --rt={min_runtime}"

jobs:
  - config: "{partition}_{nodes}nodes"
    config_jobs:
      - tag: "hpcg_{partition}"
