# Sequential is mandatory
sequential: true

variables:
  nodes: [1, 2, 4, 8]
  partition: ["eth", "ib"]

preprocess: "mkdir -p hpcg-out; cd hpcg-out; mkdir -p {partition}; cd {partition}; cp ../../hpcg.dat ."
command: "mpirun -np {nodes} ../../xhpcg"

jobs:
  - config: "{partition}_{nodes}nodes"
    config_jobs:
      - tag: "hpcg_{partition}"
