variables:
  nodes: [1, 2, 4, 8]
  partition: ["cn-ib", "cn-eth"]

baldo:
  scheduler: slurm

  default_conf:
    account: "dcn"
    ntasks: 1
    cpus_per_task: 128
    gpus: 0
    time: "01:00:00"
    modules: 
      - "GCC/14.1.0"
      - "OpenMPI/5.0.3"
    env:
      - "SKIP_VALIDATION=1"

  configs:
    - name: "{partition}_{nodes}nodes"
      partition: "cn-{partition}"
