sequential: true

variables:
  bin:
   - "graph500_bfs_2KiB"
   - "graph500_bfs_32KiB"
   - "graph500_bfs_256KiB"
   - "graph500_bfs_8MiB"
  scale: [20]
  edgefactor: [8, 16, 32]
  

command: "mpirun --allow-run-as-root --map-by node -x PATH -x LD_LIBRARY_PATH -np {nodes} --hostfile /root/hpc/tpasquali/HPC-benchmarks/NJ/{nodes}hosts_{partition} ./bin/{bin} {scale} {edgefactor}"

jobs:
  - config: "{partition}_{nodes}nodes"
    variables:
      nodes: [8, 4, 2, 1]
      partition: ['nanjing-inter']
    config_jobs:
      - tag: "graph500_{partition}"

  
  - config: "{partition}_{nodes}nodes"
    variables:
      nodes: [4, 2]
      partition: ['nanjing-intra']
    config_jobs:
      - tag: "graph500_{partition}"