sequential: true

variables:
  nodes: [4]
  # partition: ["boost_usr_prod"] # Leonardo Booster
  partition: ["eth"] #, "ib"] # HAICGU

  bin:
   - "graph500_bfs_2KiB"
   # - "graph500_bfs_8MiB"
  scale: [20]
  edgefactor: [64]

command: "mpirun -np {nodes} ./bin/{bin} {scale} {edgefactor}"

jobs:
  - config: "{partition}_{nodes}nodes"
    config_jobs:
      - tag: "graph500_{partition}"
